# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4014f1b6915c4b1bbec73c5e51a58c1f2df79dabbc808b06f667a59eb76eb5dc2333cce0b76fb9c8dd1c4211c915c59dea237555da7ea0070cd3e76bf2f0502b

test:
  secret_key_base: 4b482db1cd79c6c3b0c8f9f9329b3ba6640e87911629cc58e39567a5fd6d9bcdf2dcd571daac2ace2783d948993e6b3e4fd6dcc67cd26f07d0df3d15510c1149

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
